log:
  disable_sentry: true

client:
  endpoint: http://...

keys:
  signer: ...

doorman:
  skip_sign_check: false

notificator:
  default_channels_priority:
    - push
    - sms
    - email
  default_locale: en # Optional

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: notifications-router-svc
  service_port: 80
